--- #YAML:1.0
name:               Config-FileManager
version:            1.6
abstract:           Configuration File Management with versionning
author:
    - Alban MANCHERON <alban.mancheron@lirmm.fr>, Nicolas PHILIPPE <nicolas.philippe@inserm.fr>
license:            open_source
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:            1.17
    Data::Dumper:    2.125
    Exporter:        5.62
    File::Basename:  2.76
    File::HomeDir:   0.97
    Pod::Usage:      1.35
    POSIX:           1.13
    strict:          1.04
    Text::Diff:      1.41
    Text::Patch:     1.8
    utf8:            1.07
    warnings:        1.06
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
